# tests/contracts/test_optimal.py

"""
Comprehensive unit and integration tests for the optimal contract solver
in src/contracts/optimal.py.

This suite is designed to be the definitive validation of the nested
optimization solver. It verifies the three most critical properties of the
final generated contract across a wide variety of parameter scenarios:
1. Incentive Compatibility: Does the contract actually induce the optimal efforts?
2. Constraint Satisfaction: Does the contract satisfy the agent's utility constraints?
3. Implementability: Are all payments non-negative?
"""

import unittest
import numpy as np

from src.contracts.optimal import calculate_optimal_contract, _solve_for_optimal_efforts
from src.simulation_utils import prob_good_safety_outcome, prob_high_performance_signal
from src.agents.rational import RationalDeveloperAgent
from tests.test_rational_developer import DummyModel # Reuse the dummy model from other tests

class TestOptimalContractSolver(unittest.TestCase):

    def setUp(self):
        """Set up 10 varied parameter configurations for robust testing."""
        self.param_sets = [
            # 1. Baseline Scenario
            {'nu': 0.5, 'theta_L': 1.0, 'theta_H': 2.0, 'delta_W': 1000.0},
            # 2. High Stakes Scenario
            {'nu': 0.5, 'theta_L': 1.0, 'theta_H': 2.0, 'delta_W': 5000.0},
            # 3. Low Type Separation
            {'nu': 0.5, 'theta_L': 1.8, 'theta_H': 2.0, 'delta_W': 1000.0},
            # 4. High Prior for Good Type
            {'nu': 0.8, 'theta_L': 1.0, 'theta_H': 2.0, 'delta_W': 1000.0},
            # 5. Low Stakes Scenario
            {'nu': 0.5, 'theta_L': 1.0, 'theta_H': 2.0, 'delta_W': 100.0},
        ]

    def test_solver_end_to_end_properties(self):
        """
        A comprehensive test that verifies the critical properties of the
        contract generated by the full solver.
        """
        for params in self.param_sets:
            with self.subTest(params=params):
                # --- Act ---
                # The main call to our full solver
                contract_menu, theoretical_efforts = calculate_optimal_contract(params)

                # --- Assert ---
                # Property 1: Incentive Compatibility (Does it work?)
                # We check if a rational agent, when given the contract, actually
                # chooses the effort levels the solver intended.
                self._verify_incentive_compatibility(contract_menu, theoretical_efforts, params)

                # Property 2: Constraint Satisfaction (Are the constraints met?)
                # We manually verify that the binding IR and IC constraints are satisfied.
                self._verify_binding_constraints(contract_menu, theoretical_efforts, params)

                # Property 3: Implementability (Are payments non-negative?)
                self._verify_non_negativity(contract_menu)

    def _verify_incentive_compatibility(self, contract_menu, theoretical_efforts, params):
        """Helper to test if the contract induces the correct efforts."""
        # Test the Low-Type Agent
        low_type_agent = RationalDeveloperAgent(unique_id=1, model=DummyModel(), theta=params['theta_L'])
        low_type_agent.contract_offer = contract_menu['L']
        low_type_agent.step()
        
        self.assertAlmostEqual(low_type_agent.chosen_es, theoretical_efforts['L']['es'], places=3)
        self.assertAlmostEqual(low_type_agent.chosen_ep, theoretical_efforts['L']['ep'], places=3)
        
        # Test the High-Type Agent
        high_type_agent = RationalDeveloperAgent(unique_id=2, model=DummyModel(), theta=params['theta_H'])
        high_type_agent.contract_offer = contract_menu['H']
        high_type_agent.step()
        
        self.assertAlmostEqual(high_type_agent.chosen_es, theoretical_efforts['H']['es'], places=3)
        self.assertAlmostEqual(high_type_agent.chosen_ep, theoretical_efforts['H']['ep'], places=3)

    def _verify_binding_constraints(self, contract_menu, theoretical_efforts, params):
        """Helper to test if the utility constraints are satisfied."""
        e_pL, e_sL = theoretical_efforts['L']['ep'], theoretical_efforts['L']['es']
        e_pH, e_sH = theoretical_efforts['H']['ep'], theoretical_efforts['H']['es']

        # Verify IR-L constraint (Utility for low type should be >= 0)
        utility_L = self._calculate_utility_manually(
            efforts=(e_pL, e_sL), contract=contract_menu['L'], theta=params['theta_L']
        )
        self.assertGreaterEqual(utility_L, -1e-6)

        # Verify IC-H constraint (High type's utility must equal the TRUE mimicking utility)
        utility_H_actual = self._calculate_utility_manually(
            efforts=(e_pH, e_sH), contract=contract_menu['H'], theta=params['theta_H']
        )
        
        # To verify the IC-H constraint, we must calculate the true mimicking utility
        utility_H_mimic = self._calculate_true_mimicking_utility(
            contract_L=contract_menu['L'],
            high_type_theta=params['theta_H']
        )
        
        self.assertAlmostEqual(utility_H_actual, utility_H_mimic, places=5)
        
    def _verify_non_negativity(self, contract_menu):
        """Helper to test if all payments are non-negative."""
        for contract in contract_menu.values():
            for payment_dict in contract.values():
                for payment in payment_dict.values():
                    self.assertGreaterEqual(payment, -1e-9)

    def _calculate_utility_manually(self, efforts, contract, theta):
        """Helper to calculate expected utility for a given effort pair."""
        e_p, e_s = efforts
        cost = (e_p**2 / 2.0) + (e_s**2 / (2.0 * theta))
        p_pi_H = prob_high_performance_signal(e_p)
        p_q_G = prob_good_safety_outcome(e_s)
        
        expected_payment = (
            p_q_G * p_pi_H * contract['G']['H'] +
            p_q_G * (1 - p_pi_H) * contract['G']['L'] +
            (1 - p_q_G) * p_pi_H * contract['B']['H'] +
            (1 - p_q_G) * (1 - p_pi_H) * contract['B']['L']
        )
        return expected_payment - cost

    def _calculate_true_mimicking_utility(self, contract_L, high_type_theta):
        """
        Calculates the true utility a high-type agent gets by re-optimizing
        their effort under the low-type's contract.
        """
        # Create a temporary high-type agent to find the best response
        mimicking_agent = RationalDeveloperAgent(unique_id=99, model=DummyModel(), theta=high_type_theta)
        mimicking_agent.contract_offer = contract_L
        
        # The agent's step method runs the optimizer
        mimicking_agent.step()
        
        # Manually calculate the utility for the efforts the mimic *actually* chooses
        mimic_utility = self._calculate_utility_manually(
            efforts=(mimicking_agent.chosen_ep, mimicking_agent.chosen_es),
            contract=contract_L,
            theta=high_type_theta
        )
        return mimic_utility

if __name__ == '__main__':
    unittest.main()